# Generated by Django 2.2.1 on 2019-07-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadshape',
            options={'managed': True},
        ),
    ]
