# Generated by Django 2.2.1 on 2019-07-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_auto_20190710_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDatabase',
        ),
    ]
